"""empty message

Revision ID: 0aaaa8ce74e8
Revises: 12a8f19153fa
Create Date: 2021-02-06 08:27:02.704194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaaa8ce74e8'
down_revision = '12a8f19153fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('wait_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Waiting', 'wait_time')
    # ### end Alembic commands ###
