"""empty message

Revision ID: 195016410688
Revises: e90ce56c2543
Create Date: 2021-02-06 23:15:03.242308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195016410688'
down_revision = 'e90ce56c2543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('wait_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Waiting', 'wait_time')
    # ### end Alembic commands ###
