"""empty message

Revision ID: 2134ee0bd0bf
Revises: 2e8eda6d1ddd
Create Date: 2021-02-07 11:50:02.140562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2134ee0bd0bf'
down_revision = '2e8eda6d1ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Supermarket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('timetable', sa.JSON(), nullable=False),
    sa.Column('waiting_time', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mean_shopping_time', sa.Integer(), server_default='10', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Supermarket')
    # ### end Alembic commands ###
