"""empty message

Revision ID: 27e9b4211e04
Revises: 8c534a96fe67
Create Date: 2021-01-30 13:53:32.794395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e9b4211e04'
down_revision = '8c534a96fe67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Supermarket', sa.Column('mean_shopping_time', sa.Integer(), nullable=False))
    op.add_column('Supermarket', sa.Column('waiting_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Supermarket', 'waiting_time')
    op.drop_column('Supermarket', 'mean_shopping_time')
    # ### end Alembic commands ###
