"""empty message

Revision ID: 28fe9fb6187c
Revises: 8ab531ed8b17
Create Date: 2021-02-06 23:16:32.231503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fe9fb6187c'
down_revision = '8ab531ed8b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('wait_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Waiting', 'wait_time')
    # ### end Alembic commands ###
