"""empty message

Revision ID: 668ba9433f39
Revises: cb5844d0c5d0
Create Date: 2021-02-04 07:24:19.983582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '668ba9433f39'
down_revision = 'cb5844d0c5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.drop_column('Waiting', 'waiting_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('waiting_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Waiting', 'date_time')
    # ### end Alembic commands ###
