"""empty message

Revision ID: 6e603a1af399
Revises: 0aaaa8ce74e8
Create Date: 2021-02-06 08:35:41.207305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e603a1af399'
down_revision = '0aaaa8ce74e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('wait_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Waiting', 'wait_time')
    # ### end Alembic commands ###
