"""empty message

Revision ID: 728f89d94e63
Revises: 8716bb48a645
Create Date: 2021-02-03 21:06:11.298692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728f89d94e63'
down_revision = '8716bb48a645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supermarket_id', sa.Integer(), nullable=False),
    sa.Column('enter_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Request', sa.Column('token', sa.String(), nullable=False))
    op.add_column('Waiting', sa.Column('token', sa.String(), nullable=False))
    op.drop_column('Waiting', 'request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Waiting', 'token')
    op.drop_column('Request', 'token')
    op.drop_table('Record')
    # ### end Alembic commands ###
