"""empty message

Revision ID: 81b7cf39cf40
Revises: 27e9b4211e04
Create Date: 2021-01-30 14:06:58.080946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b7cf39cf40'
down_revision = '27e9b4211e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Supermarket', sa.Column('mean_shopping_time', sa.Integer(), server_default='10', nullable=True))
    op.add_column('Supermarket', sa.Column('waiting_time', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Supermarket', 'waiting_time')
    op.drop_column('Supermarket', 'mean_shopping_time')
    # ### end Alembic commands ###
