"""empty message

Revision ID: 845374b9ef29
Revises: 81b7cf39cf40
Create Date: 2021-01-30 14:07:56.851092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845374b9ef29'
down_revision = '81b7cf39cf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Supermarket', 'mean_shopping_time',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('Supermarket', 'waiting_time',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Supermarket', 'waiting_time',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('Supermarket', 'mean_shopping_time',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    # ### end Alembic commands ###
