"""empty message

Revision ID: 8eeef957ed85
Revises: 28fe9fb6187c
Create Date: 2021-02-06 23:16:46.558068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eeef957ed85'
down_revision = '28fe9fb6187c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Waiting', 'wait_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Waiting', 'wait_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
