"""empty message

Revision ID: a60505c93270
Revises: 2134ee0bd0bf
Create Date: 2021-02-07 12:05:38.756185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60505c93270'
down_revision = 'c3f78dcf9720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('type_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Waiting', 'type_id')
    # ### end Alembic commands ###
