"""empty message

Revision ID: a87ad124b510
Revises: d4f37c13cf73
Create Date: 2021-02-03 22:53:15.327700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87ad124b510'
down_revision = 'd4f37c13cf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Request', sa.Column('username', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'Request', ['username'])
    op.create_unique_constraint(None, 'Shopping', ['username'])
    op.add_column('Waiting', sa.Column('waiting_time', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'Waiting', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Waiting', type_='unique')
    op.drop_column('Waiting', 'waiting_time')
    op.drop_constraint(None, 'Shopping', type_='unique')
    op.drop_constraint(None, 'Request', type_='unique')
    op.drop_column('Request', 'username')
    # ### end Alembic commands ###
