"""empty message

Revision ID: c3f78dcf9720
Revises: 4f109a49e029
Create Date: 2021-02-07 20:17:00.446585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f78dcf9720'
down_revision = '4f109a49e029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('enter_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Waiting', 'enter_time')
    # ### end Alembic commands ###
