"""empty message

Revision ID: cb5844d0c5d0
Revises: a87ad124b510
Create Date: 2021-02-04 00:22:28.340001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb5844d0c5d0'
down_revision = 'a87ad124b510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Record', sa.Column('delta_time', sa.Integer(), nullable=False))
    op.drop_column('Record', 'exit_time')
    op.drop_column('Record', 'enter_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Record', sa.Column('enter_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Record', sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Record', 'delta_time')
    # ### end Alembic commands ###
