"""empty message

Revision ID: d0f5764264d9
Revises: bcc52b198f8f
Create Date: 2021-02-06 18:32:50.823419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f5764264d9'
down_revision = 'bcc52b198f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('type_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Waiting', 'type_id')
    # ### end Alembic commands ###
