"""empty message

Revision ID: d4f37c13cf73
Revises: 728f89d94e63
Create Date: 2021-02-03 21:21:31.959903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f37c13cf73'
down_revision = '728f89d94e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shopping', sa.Column('token', sa.String(), nullable=False))
    op.drop_column('Shopping', 'request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shopping', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Shopping', 'token')
    # ### end Alembic commands ###
