"""empty message

Revision ID: df7fd0ea7643
Revises: a7d654cc87d2
Create Date: 2021-01-29 13:58:32.229355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7fd0ea7643'
down_revision = 'a7d654cc87d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Supermarket', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('Supermarket', sa.Column('lon', sa.Float(), nullable=False))
    op.add_column('Supermarket', sa.Column('timetable', sa.JSON(), nullable=False))
    op.alter_column('Supermarket', 'logo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Supermarket', 'coordinates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Supermarket', sa.Column('coordinates', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('Supermarket', 'logo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Supermarket', 'timetable')
    op.drop_column('Supermarket', 'lon')
    op.drop_column('Supermarket', 'lat')
    # ### end Alembic commands ###
