"""empty message

Revision ID: e90ce56c2543
Revises: 0590d6335620
Create Date: 2021-02-06 09:45:34.630933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90ce56c2543'
down_revision = '0590d6335620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Waiting', 'wait_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Waiting', sa.Column('wait_time', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
